fernetKey:  M05McHhLTzNMZkRQMmdSRENKWnV4eWZwTFR4d200b2I=
webserverSecretKey:  M05McHhLTzNMZkRQMmdSRENKWnV4eWZwTFR4d200b2I=
executor: "KubernetesExecutor"

dags:
  gitSync:
    enabled: true
    repo: https://github.com/airscholar/Kubernetes-For-DataEngineering.git
    branch: main
    rev: HEAD
    depth: 1
    maxFailures: 0
    subPath: "dags"